# Generated by Django 6.0.5 on 2026-05-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='arbiter_notes',
            field=models.TextField(blank=True),
        ),
    ]
