# Generated by Django 6.0.5 on 2026-05-20 06:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_techniciandocument"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Auction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField()),
                ("location", models.CharField(blank=True, max_length=160)),
                ("urgency", models.CharField(default="normal", max_length=20)),
                (
                    "budget_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "budget_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("awarded", "Awarded"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("telegram", "Telegram"), ("dashboard", "Dashboard")],
                        default="dashboard",
                        max_length=20,
                    ),
                ),
                ("closes_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="auctions",
                        to="catalog.category",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auctions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auctions",
                        to="catalog.zone",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Bid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("estimated_minutes", models.PositiveIntegerField(default=60)),
                ("available_from", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "auction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to="auctions.auction",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bids",
                        to="catalog.service",
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to="catalog.technicianprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["amount", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="auction",
            name="winning_bid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="auctions.bid",
            ),
        ),
        migrations.AddIndex(
            model_name="bid",
            index=models.Index(fields=["auction"], name="bid_auction_idx"),
        ),
        migrations.AddIndex(
            model_name="bid",
            index=models.Index(fields=["technician"], name="bid_technician_idx"),
        ),
        migrations.AddIndex(
            model_name="bid",
            index=models.Index(fields=["status"], name="bid_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="bid",
            constraint=models.UniqueConstraint(
                fields=("auction", "technician"),
                name="unique_bid_per_technician_auction",
            ),
        ),
        migrations.AddIndex(
            model_name="auction",
            index=models.Index(fields=["client"], name="auction_client_idx"),
        ),
        migrations.AddIndex(
            model_name="auction",
            index=models.Index(fields=["status"], name="auction_status_idx"),
        ),
        migrations.AddIndex(
            model_name="auction",
            index=models.Index(fields=["category"], name="auction_category_idx"),
        ),
    ]
