# Generated by Django 5.2.14 on 2026-05-25 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
