# Generated by Django 5.2.14 on 2026-05-18 23:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('leads', '0002_servicelead_client_user'),
        ('reputation', '0002_mutual_ratings_and_penalties'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rating',
            name='rating_target_matches_role',
        ),
        migrations.AlterField(
            model_name='penalty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='target_role',
            field=models.CharField(choices=[('technician', 'Technician'), ('client', 'Client')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('client__isnull', True), ('target_role', 'technician'), ('technician__isnull', False)), models.Q(('client__isnull', False), ('target_role', 'client'), ('technician__isnull', True)), _connector='OR'), name='rating_target_matches_role'),
        ),
    ]
