# Generated by Django 6.0.5 on 2026-05-12 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=160)),
                ('client_phone', models.CharField(max_length=40)),
                ('message', models.TextField()),
                ('category', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('urgency', models.CharField(default='normal', max_length=20)),
                ('source', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('dashboard', 'Dashboard')], default='whatsapp', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('accepted', 'Accepted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='catalog.service')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='catalog.technicianprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
