# Generated by Django 6.0.5 on 2026-05-18 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WhatsAppConversation',
            new_name='TelegramConversation',
        ),
    ]
